### ISSUE TITLE
Баги по туториалу

### ISSUE THREAD

**Issue by KirillDmit** [IlyaOlokin/TacticTowers2#17]
1) Прокачка не той башни приводит к зависанию на уровне
2) Попытка рестартнуть обучение выдаёт UnassignedReferenceException
3) Если противники зайдут на базу, то чел всё равно молодец. Ну как бы ок

**Comment by Nakofu** [comment]
1) если вкачать не правую, а верхнюю, то обучение нельзя будет завершить
2) кнопки меню и заново не работает (вроде из за отсутствия confirmPanel)
3) надо все как нибудь ускорить подход врагов
4) за врагов в обучении дают кредиты - надо придумать что с этим делать (сохранять набранные кредиты или нет)
